release-1.3.0
extreal-dev/Extreal.Dev pull request #6
Opened 2024-02-26 05:24 UTC by mahaweilu

2024-02-27 02:49 UTC, sus-taguchi-t requested changes

2024-02-27 02:49 UTC, sus-taguchi-t commented on Assets/packages.config
> +  <package ID="System.Text.Encodings.Web" Version="7.0.0" TargetFramework="netstandard2.0" AllowedVersions="[7.0.0, )" />
`System.Text.Json` 等のバージョンがダウングレードしているのは何か理由があるのでしょうか？

2024-02-27 04:22 UTC, mahaweilu commented on Assets/packages.config
> +  <package ID="System.Text.Encodings.Web" Version="7.0.0" TargetFramework="netstandard2.0" AllowedVersions="[7.0.0, )" />
>何か理由があるのでしょうか？
Newtonsoft.Jsonインストールしたらバージョンダウンされてしまったようです。意図しなかったので以下で戻しました。
[912be91](https://github.com/extreal-dev/Extreal.Dev/pull/6/commits/912be91b493ec7d1d99b99127d76caee823194f5)

2024-02-27 06:09 UTC, sus-taguchi-t commented on Assets/packages.config
> +  <package ID="System.Text.Encodings.Web" Version="7.0.0" TargetFramework="netstandard2.0" AllowedVersions="[7.0.0, )" />
確認しました。

2024-04-09 05:43 UTC, sus-taguchi-t approved these changes

2024-04-09 05:43 UTC, merged